// SPDX-License-Identifier: BUSL-1.1

//! A dense index per `crate::Error` variant.

/// The number of `crate::Error` variants [`error_variant_index`] numbers.
pub(super) const ERROR_VARIANT_COUNT: usize = 116;

/// A dense index per `crate::Error` variant. Exhaustive, so a new variant
/// fails to compile here until it gets an index, and
/// [`every_error_variant_has_a_sample`] then fails until
/// [`error_samples`] carries it.
pub(crate) fn error_variant_index(err: &crate::Error) -> usize {
    use crate::Error as E;
    match err {
        E::RejectedConstraint { .. } => 0,
        E::TxnOverlayMemoryExceeded { .. } => 1,
        E::RejectedAuthz { .. } => 2,
        E::OffsetRegression { .. } => 3,
        E::DeadlineExceeded { .. } => 4,
        E::ConflictRetry { .. } => 5,
        E::CalvinSerializationConflict => 6,
        E::CalvinParticipantError => 7,
        E::RejectedPrevalidation { .. } => 8,
        E::RetryableRefusal { .. } => 9,
        E::AppendOnlyViolation { .. } => 10,
        E::BalanceViolation { .. } => 11,
        E::MaterializedSumTargetNotFound { .. } => 12,
        E::MaterializedSumResolutionMissing { .. } => 13,
        E::PeriodLocked { .. } => 14,
        E::PeriodLockMisconfigured { .. } => 15,
        E::RetentionViolation { .. } => 16,
        E::LegalHoldActive { .. } => 17,
        E::StateTransitionViolation { .. } => 18,
        E::TransitionCheckViolation { .. } => 19,
        E::TypeGuardViolation { .. } => 20,
        E::TypeMismatch { .. } => 21,
        E::InsufficientBalance { .. } => 22,
        E::RateExceeded { .. } => 23,
        E::CollectionNotFound { .. } => 24,
        E::DocumentNotFound { .. } => 25,
        E::CollectionDeactivated { .. } => 26,
        E::VShardAdmissionCapacityExceeded { .. } => 27,
        E::CrdtAdmissionRetriesExhausted { .. } => 28,
        E::CrdtAdmissionInvalidPlan { .. } => 29,
        E::CrdtAdmissionCallerFence => 30,
        E::CrdtApplyRequiresAdmission => 31,
        E::CrdtApplyForbiddenInTransaction => 32,
        E::NotInTransactionBlock { .. } => 33,
        E::CrdtAdmissionTimeout { .. } => 34,
        E::NoLeader { .. } => 35,
        E::NotLeader { .. } => 36,
        E::CrossCollectionNotColocated { .. } => 38,
        E::CloneWriteRequiresMaterialize { .. } => 40,
        E::BadRequest { .. } => 41,
        E::BackupTenantMismatch { .. } => 42,
        E::BackupKeyMismatch => 43,
        E::QuotaOvercommit { .. } => 44,
        E::PlanError { .. } => 45,
        E::FeatureNotSupported { .. } => 46,
        E::UndefinedFunction { .. } => 47,
        E::UndefinedObject { .. } => 48,
        E::ObjectNotInPrerequisiteState { .. } => 49,
        E::UndefinedColumn { .. } => 50,
        E::TextColumn { .. } => 115,
        E::AmbiguousColumn { .. } => 51,
        E::UnknownStrictField { .. } => 52,
        E::DivisionByZero => 53,
        E::DataException { .. } => 54,
        E::InvalidLimitValue { .. } => 55,
        E::RetryableSchemaChanged { .. } => 56,
        E::RetryableLeaderChange { .. } => 57,
        E::GroupQuorumUnavailable { .. } => 58,
        E::GroupMarksUnavailable { .. } => 59,
        E::MetadataLeaderUnavailable => 60,
        E::AuthorizationStateBehind { .. } => 61,
        E::ExecutionLimitExceeded { .. } => 62,
        E::LimitExceeded { .. } => 63,
        E::Wal(_) => 64,
        E::Dispatch { .. } => 65,
        E::DispatchCapacity { .. } => 66,
        E::Storage { .. } => 67,
        E::ColdStorage { .. } => 68,
        E::Serialization { .. } => 69,
        E::Codec { .. } => 70,
        E::SegmentCorrupted { .. } => 71,
        E::MemoryExhausted { .. } => 72,
        E::Backpressure { .. } => 73,
        E::Crdt(_) => 74,
        E::Io(_) => 75,
        E::Config { .. } => 76,
        E::Encryption { .. } => 77,
        E::Bridge { .. } => 78,
        E::VersionCompat { .. } => 79,
        E::Internal { .. } => 80,
        E::Shaping(_) => 81,
        E::RemoteTyped { .. } => 82,
        E::DescriptorVersionAnomaly { .. } => 83,
        E::CollectionPurgeRowMissing { .. } => 84,
        E::CatalogIntegrityViolation { .. } => 85,
        E::DataPlane(_) => 86,
        E::Promql(_) => 87,
        E::DependentObjectsExist { .. } => 88,
        E::CascadeCycle { .. } => 89,
        E::CrossShardInExplicitTransaction => 90,
        E::SequencerUnavailable => 91,
        E::SessionCapExceeded { .. } => 92,
        E::SessionIdleTimeout => 93,
        E::SessionTokenExpired => 94,
        E::SessionKilledByAdmin => 95,
        E::SessionUserDropped => 96,
        E::OidcProviderTenantUnbound => 97,
        E::OidcProviderTenantUnavailable { .. } => 98,
        E::ExternalRoleUndefined { .. } => 99,
        E::OidcNoDefaultDatabase { .. } => 100,
        E::TenantVectorDimExceeded { .. } => 101,
        E::TenantGraphDepthExceeded { .. } => 102,
        E::RoleInheritanceCycle { .. } => 103,
        E::RoleInheritanceDepthExceeded { .. } => 104,
        E::OllpExhausted { .. } => 105,
        E::MirrorReadOnly { .. } => 106,
        E::StaleReadNotLeader { .. } => 107,
        E::RoleInUse { .. } => 108,
        E::Ddl(_) => 109,
        E::LinearizableReadRefused { .. } => 110,
        E::CommittedResultUnavailable { .. } => 111,
        E::ProposalOutcomeUnknown { .. } => 39,
        E::RestoreTargetNotEmpty { .. } => 112,
        E::RestoreVerificationFailed { .. } => 113,
        E::BackupCaptureMoved { .. } => 114,
        E::CollectionUnstamped { .. } => 37,
    }
}
