// SPDX-License-Identifier: BUSL-1.1

//! [`ReplicatedEntry`] — the routing envelope carried alongside a
//! [`super::ReplicatedWrite`] on the Raft log, plus its (de)serialization.

use super::replicated_write::ReplicatedWrite;

/// Metadata carried alongside the write for routing on the receiving node.
#[derive(
    Debug,
    Clone,
    serde::Serialize,
    serde::Deserialize,
    zerompk::ToMessagePack,
    zerompk::FromMessagePack,
)]
pub struct ReplicatedEntry {
    pub tenant_id: u64,
    /// Database scope for the write. `0` decodes to `DatabaseId::DEFAULT`.
    ///
    /// This struct's zerompk representation is a plain positional array (no
    /// `#[msgpack(map)]`), so adding this field changed the array length from
    /// 4 to 5. An entry proposed by a not-yet-upgraded leader (still emitting
    /// the 4-element shape) would otherwise fail `check_array_len` on a new
    /// follower. `ReplicatedEntry::from_bytes` handles that case explicitly
    /// by falling back to `super::legacy_entry::LegacyReplicatedEntry` (the
    /// pre-`database_id` 4-field shape) and defaulting `database_id` to `0`.
    #[serde(default)]
    pub database_id: u64,
    pub vshard_id: u32,
    /// Per-proposal idempotency key. Generated by the proposer when the
    /// entry is constructed and embedded in the Raft log payload so the
    /// apply path can match the entry that actually committed at a given
    /// `(group_id, log_index)` against the entry the proposer is waiting
    /// for. A mismatch means a leader change overwrote the proposer's
    /// reservation with a different proposer's entry — the apply path
    /// surfaces `RetryableLeaderChange` so the gateway re-proposes.
    ///
    /// Zero is reserved as "no key" (legacy / synthetic entries that
    /// pre-date the field). The tracker treats `0` as a wildcard to
    /// preserve backwards compatibility with any in-flight log on
    /// upgrade.
    pub idempotency_key: u64,
    pub write: ReplicatedWrite,
    /// HLC wall time, in nanoseconds, at which the proposer committed to the
    /// write. Stamped once before the first propose, so a re-proposal keeps
    /// it. Every replica records it as the write's instant on the tenant's
    /// observed write high-water, however late it applies. `0` for an entry
    /// proposed without one; its apply stamps the instant of its own append.
    pub write_hlc: u64,
    /// The metadata-group index the proposer had applied when it proposed
    /// the write. Every replica applies the write only once its own metadata
    /// apply reached this index, so the write never lands against an older
    /// catalog than the one it was planned against: a same-name collection's
    /// pending purge has reclaimed its storage, and the collection the write
    /// targets is registered. `0` for an entry proposed without one.
    pub metadata_floor: u64,
}

impl ReplicatedEntry {
    /// Construct a new `ReplicatedEntry` with a freshly generated
    /// idempotency key. All production write paths go through this
    /// constructor; only deserialized log entries skip it (the key is
    /// preserved through `from_bytes`).
    pub fn new(tenant_id: u64, database_id: u64, vshard_id: u32, write: ReplicatedWrite) -> Self {
        // OR with 1 so the LSB is set: zero is reserved as the "no key"
        // sentinel and a fresh `rand::random::<u64>()` could in principle
        // hit zero (P ~= 2^-64 but cheap to make impossible).
        let idempotency_key = rand::random::<u64>() | 1;
        Self {
            tenant_id,
            database_id,
            vshard_id,
            idempotency_key,
            write,
            write_hlc: 0,
            metadata_floor: 0,
        }
    }

    /// Serialize to bytes for Raft log entry data.
    pub fn to_bytes(&self) -> Vec<u8> {
        zerompk::to_msgpack_vec(self).expect("ReplicatedEntry serialization cannot fail")
    }

    /// Deserialize from Raft log entry data bytes.
    ///
    /// Tries the current 7-field shape first. If that fails specifically
    /// because the encoded array is the pre-`database_id` 4-element shape
    /// (an entry proposed by an old leader still mid-upgrade), falls back to
    /// [`super::legacy_entry::LegacyReplicatedEntry`] and defaults
    /// `database_id` to `0` (`DatabaseId::DEFAULT`). Any other decode error
    /// (corrupt data, genuinely unrelated shape) returns `None`, matching
    /// prior behavior.
    pub fn from_bytes(data: &[u8]) -> Option<Self> {
        match zerompk::from_msgpack::<Self>(data) {
            Ok(entry) => Some(entry),
            Err(zerompk::Error::ArrayLengthMismatch { actual, .. })
                if actual == super::super::legacy_entry::LegacyReplicatedEntry::FIELD_COUNT =>
            {
                zerompk::from_msgpack::<super::super::legacy_entry::LegacyReplicatedEntry>(data)
                    .ok()
                    .map(super::super::legacy_entry::LegacyReplicatedEntry::into_current)
            }
            Err(_) => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::bridge::envelope::PhysicalPlan;
    use crate::control::wal_replication::decode;
    use crate::types::{DatabaseId, TenantId, VShardId};
    use nodedb_physical::physical_plan::DocumentOp;
    use nodedb_types::{QualifiedCollection, Surrogate};

    /// Decide + encode in one call, so each test names only the plan it encodes.
    fn to_replicated_entry(
        tenant_id: TenantId,
        database_id: DatabaseId,
        vshard_id: VShardId,
        plan: &PhysicalPlan,
    ) -> crate::Result<Option<ReplicatedEntry>> {
        let write = crate::control::wal_replication::ReplicableWrite::decide_for_replication(plan)?;
        crate::control::wal_replication::encode::to_replicated_entry(
            tenant_id,
            database_id,
            vshard_id,
            &write,
        )
    }

    #[test]
    fn replicated_entry_roundtrip() {
        let entry = ReplicatedEntry::new(
            1,
            0,
            42,
            ReplicatedWrite::PointPut {
                collection: "users".into(),
                document_id: "u1".into(),
                value: b"alice".to_vec(),
                surrogate: 1,
                resolved_sum_targets: Vec::new(),
                resolved_sum_target_bindings: Vec::new(),
                returning: None,
                rls_filters: Vec::new(),
            },
        );
        let original_key = entry.idempotency_key;
        assert_ne!(original_key, 0, "idempotency_key must be non-zero");

        let bytes = entry.to_bytes();
        let decoded = ReplicatedEntry::from_bytes(&bytes).unwrap();
        assert_eq!(decoded.tenant_id, 1);
        assert_eq!(decoded.vshard_id, 42);
        assert_eq!(
            decoded.idempotency_key, original_key,
            "idempotency_key roundtrip"
        );
        match decoded.write {
            ReplicatedWrite::PointPut {
                collection,
                document_id,
                value,
                surrogate,
                resolved_sum_targets,
                resolved_sum_target_bindings,
                returning,
                rls_filters,
            } => {
                assert_eq!(collection, "users");
                assert_eq!(document_id, "u1");
                assert_eq!(value, b"alice");
                assert_eq!(surrogate, 1);
                assert!(resolved_sum_targets.is_empty());
                assert!(resolved_sum_target_bindings.is_empty());
                assert_eq!(returning, None);
                assert!(rls_filters.is_empty());
            }
            other => panic!("expected PointPut, got {other:?}"),
        }
    }

    #[test]
    fn non_default_database_id_roundtrips_through_encode_decode() {
        let tenant = TenantId::new(1);
        let database = DatabaseId::new(1024);
        let vshard = VShardId::new(0);

        let plan = PhysicalPlan::Document(DocumentOp::PointPut {
            collection: QualifiedCollection::new(DatabaseId::DEFAULT, "c"),
            document_id: "d".into(),
            value: vec![1, 2, 3],
            surrogate: Surrogate::ZERO,
            pk_bytes: Vec::new(),
            returning: None,
            rls_filters: Vec::new(),
            resolved_sum_targets: Vec::new(),
        });

        let entry = to_replicated_entry(tenant, database, vshard, &plan)
            .expect("encode must not error")
            .expect("PointPut should produce a ReplicatedEntry");
        assert_eq!(entry.database_id, database.as_u64());

        let bytes = entry.to_bytes();
        let decoded_entry = ReplicatedEntry::from_bytes(&bytes).expect("decode failed");
        assert_eq!(
            decoded_entry.database_id,
            database.as_u64(),
            "database_id must survive the byte round-trip"
        );

        let (_, _, decoded_plan, _) = decode::from_replicated_entry(&bytes, None)
            .expect("from_replicated_entry error")
            .expect("from_replicated_entry returned None");
        match decoded_plan {
            PhysicalPlan::Document(DocumentOp::PointPut { collection, .. }) => {
                assert_eq!(collection.as_str(), "c");
            }
            other => panic!("expected Document(PointPut), got {other:?}"),
        }
    }
}
